feat(#2252): enhance data lake sink schema management options
apache/streampipes pull request #2263
Opened 2023-12-03 12:29 UTC by tenthe

### Purpose

Add option to merge existing event schemas with the new one of data lake measurements.

### Remarks

PR introduces (a) breaking change(s): yes

PR introduces (a) deprecation(s): no

2023-12-05 07:37 UTC, bossenti requested changes

2023-12-05 07:37 UTC, bossenti commented on streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/DataExplorerSchemaManagement.java
> +    return new ArrayList<>(
```java
// Combine the event properties from both measures into a single Stream
    var allMeasurementProperties = Stream.concat(
        measure1.getEventSchema()
                .getEventProperties()
                .stream(),
        measure2.getEventSchema()
                .getEventProperties()
                .stream()
    );
    
    // Filter event properties by removing duplicate runtime names
    // If there are duplicate keys, choose the first occurrence
    var unifiedEventProperties = allMeasurementProperties
        .collect(Collectors.toMap(
            EventProperty::getRuntimeName,
            Function.identity(),
            (eventProperty, eventProperty2) -> eventProperty
        ))
        .values();
    return new ArrayList<>(unifiedEventProperties);
```

How do you like this?

2023-12-05 07:37 UTC, bossenti commented on streampipes-extensions/streampipes-sinks-internal-jvm/src/main/java/org/apache/streampipes/sinks/internal/jvm/datalake/DataLakeSink.java
> +            Options.from("Update schema", "Extend existing schema")
Can we move the labelNames to `DataLakeMeasureSchemaUpdateStrategy`?
This would allow us to refer to the labels instead of writing them again

2023-12-05 07:37 UTC, bossenti commented on streampipes-extensions/streampipes-sinks-internal-jvm/src/main/java/org/apache/streampipes/sinks/internal/jvm/migration/DataLakeSinkMigrationV1.java
> +    var label = Labels.from(
`Labels.from` is deprecated. Is there no other solution?

2023-12-05 07:37 UTC, bossenti commented on streampipes-rest/src/main/java/org/apache/streampipes/rest/ResetManagement.java
> +    IDataExplorerSchemaManagement dataLakeMeasureManagement = new DataExplorerSchemaManagement(dataLakeStorage);
```suggestion
    var dataExplorerSchemaManagement = new DataExplorerSchemaManagement(dataLakeStorage);
```

2023-12-05 07:37 UTC, bossenti commented on ui/src/app/core-services/template/PipelineInvocationBuilder.ts
> +import { optionsProviders } from '@danielmoncada/angular-datetime-picker';
Is this import required?

2023-12-05 09:49 UTC, tenthe commented on streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/DataExplorerSchemaManagement.java
> +      if (document.get("measureName")
I am not sure. I'd rather cover this in a separate PR as this PR focuses on the schema update strategy. Ok? The changes are only a reformatting of the exising code.

2023-12-05 11:41 UTC, bossenti commented on streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/DataExplorerSchemaManagement.java
> +      if (document.get("measureName")
Yes, sure. No need to take care of it right now.

2023-12-05 11:43 UTC, bossenti commented on streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/DataExplorerSchemaManagement.java
> +  private static void setDefaultUpdateStrategyIfNoneProvided(DataLakeMeasure measure) {
Okay 👍🏼 
Do we then need to adapt the client(s) as well?
Just so that we can create the issues and don't forget about it 🙂

2023-12-05 11:45 UTC, bossenti commented on ui/package.json
> +    "echarts-wordcloud": "^2.1.0",
Are the changes here by accident?

2023-12-06 10:45 UTC, bossenti commented on streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/DataExplorerSchemaManagement.java
> +      if (document.get("measureName")
https://github.com/apache/streampipes/issues/2281

2023-12-06 10:48 UTC, bossenti commented on streampipes-data-explorer/src/main/java/org/apache/streampipes/dataexplorer/DataExplorerSchemaManagement.java
> +  private static void setDefaultUpdateStrategyIfNoneProvided(DataLakeMeasure measure) {
https://github.com/apache/streampipes/issues/2282

2023-12-06 10:48 UTC, bossenti approved these changes

2023-12-06 11:16 UTC, merged